/*
 * Copyright (c) 2023. Smart Operating Block
 *
 * Use of this source code is governed by an MIT-style
 * license that can be found in the LICENSE file or at
 * https://opensource.org/licenses/MIT.
 */

package presenter

import entities.TelemetrySystem

/**
 * Represent a generic deserializer of the data generated by the telemetry system.
 */
interface Deserializer {

    /**
     * Given the data of the telemetry system, deserialize them.
     */
    fun deserialize(data: String): TelemetrySystem
}
